export const LOAD_PROFILE_DATA_INITIATED = "LOAD_PROFILE_DATA_INITIATED";
export const LOAD_PROFILE_DATA_SUCCESS = "LOAD_PROFILE_DATA_SUCCESS";
export const LOAD_PROFILE_DATA_ERROR = "LOAD_PROFILE_DATA_ERROR";
